faq/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('faq/create/', views.faq_create, name="faq-create"),
    path('faq/display/', views.faq_display, name="faq-display"),
    path('faq/list/', views.faq_list, name="faq-list"),
    path('faq/delete/<int:faq_id>/', views.faq_delete, name="faq-delete"),
    path('faq/edit/<int:faq_id>/', views.faq_edit, name="faq-edit"),
]

fdip/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('industry.urls')),
    path('', include('accounts.urls')),
    path('', include('report.urls')),
    path('', include('faq.urls')),
    path('', include('industry_without_gis.urls')),
    path('', include('improv.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

industry_without_gis/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('industry-without-gis/home/', views.industry_without_gis_home, name="industry_without_gis_home"),
    path('industry-without-gis/list/', views.without_gis_industry_list, name="industry_without_gis_list"),
    path('industry-ajax-search-without-gis/', views.AjaxSearchWithousGis, name="AjaxSearchWithoutGis"),
    path('industry-without-gis/session-reset/', views.session_delete, name="session_reset_without_gis"),
    path('industry-without-gis/profile/<int:industry_id>/', views.view_industry_profile_without_gis, name="industry_profile_without_gis"),
    path('industry-without-gis/delete/<int:industry_id>/', views.delete_industry_without_gis, name="industry_delete_without_gis"),
    path('industry-without-gis/edit/<int:industry_id>/', views.edit_industry_without_gis, name="edit_industry_without_gis"),
    path('industry-without-gis/download/excel/', views.without_gis_industry_excel, name="without_gis_excel"),
    path('industry-without-gis/download/csv/', views.without_gis_industry_csv, name="without_gis_csv"),
    path('industry-without-gis-profile/download/pdf/<int:industry_id>/', views.industry_without_gis_profile_pdf, name="industry_without_gis_profile_pdf"),
    path('industry-without-gis/download/pdf/', views.without_gis_download_pdf, name="industry_without_gis_download_pdf"), 
    
    # path('translation_settings/', views.translation_settings, name='translation_settings'),
]

industry_without_gis/models.py
from django.db import models

from industry.validators import nepali_date_validator
from industry.utils import get_choice_display_value
from fdip import commons


class IndustryWithoutGis(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    industry_name = models.CharField(max_length=255, blank=True, null=True)
    industry_reg_no = models.CharField(max_length=255, blank=True, null=True)
    reg_date = models.CharField(max_length=20, validators=[nepali_date_validator], blank=True, null=True)
    owner_name = models.CharField(max_length=400, blank=True, null=True)
    sex = models.CharField(max_length=6, choices=commons.SEX_CHOICES, blank=True, null=True)
    caste = models.CharField(max_length=8, choices=commons.CASTE_CHOICES, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    telephone_number = models.CharField(max_length=15, blank=True, null=True)
    contact_person = models.CharField(max_length=100, blank=True, null=True)
    mobile_number = models.CharField(max_length=15, blank=True, null=True)
    
    district = models.CharField(max_length=20, choices=commons.DISTRICT_CHOICES, blank=True, null=True)
    local_body = models.CharField(max_length=100, choices=commons.ALL_LOCALBODY_CHOICES, blank=True, null=True)
    ward_no = models.CharField(max_length=100, blank=True, null=True)
    settlement = models.CharField(max_length=100, blank=True, null=True)
    
    product_description = models.TextField(max_length=600, blank=True, null=True)
    investment = models.CharField(max_length=9, choices=commons.INVESTMENT_CHOICES, blank=True, null=True)
    ownership = models.CharField(max_length=11, choices=commons.OWNERSHIP_CHOICES, blank=True, null=True)
    raw_material_source = models.CharField(max_length=8, choices=commons.MATERIAL_SOURCE, blank=True, null=True)
    industry_acc_product = models.CharField(max_length=50, choices=commons.TYPE_OF_PRODUCT, blank=True, null=True)
    others_text = models.CharField(max_length=255, blank=True, null=True)
    current_status = models.CharField(max_length=8, choices=commons.CURRENT_STATUS, blank=True, null=True)
    current_running_capacity = models.CharField(max_length=1, choices=commons.CAPACITY, blank=True, null=True)
    machinery_tool = models.TextField(max_length=600, blank=True, null=True)
    product_service_name = models.CharField(max_length=100, blank=True, null=True)
    yearly_capacity = models.FloatField(default=0, blank=True, null=True)
    
    total_manpower = models.IntegerField(default=0, blank=True, null=True)
    skillfull = models.IntegerField(default=0, blank=True, null=True)
    unskilled = models.IntegerField(default=0, blank=True, null=True)
    indigenous = models.IntegerField(default=0, blank=True, null=True)
    foreign = models.IntegerField(default=0, blank=True, null=True)
    male = models.IntegerField(default=0, blank=True, null=True)
    female = models.IntegerField(default=0, blank=True, null=True)
    fixed_capital = models.FloatField(default=0, blank=True, null=True)
    current_capital = models.FloatField(default=0, blank=True, null=True)
    total_capital = models.FloatField(default=0, blank=True, null=True)
    
    def __str__(self):
        return self.industry_name
    
    def save(self, *args, **kwargs):
        """Overriding save method so that others text is only stored for those industries whose 
        industry_acc_product is selected as others"""
        if self.industry_acc_product != 'O':
            self.others_text = None
        super().save(*args, **kwargs)
        
    @property
    def sex_display_value(self):
        return get_choice_display_value(self.sex, commons.SEX_CHOICES)
    
    @property
    def caste_display_value(self):
        return get_choice_display_value(self.caste, commons.CASTE_CHOICES)
    
    @property
    def investment_display_value(self):
        return get_choice_display_value(self.investment, commons.INVESTMENT_CHOICES)
    
    @property
    def industry_acc_product_display_value(self):
        return get_choice_display_value(self.industry_acc_product, commons.TYPE_OF_PRODUCT)
    
    @property
    def ownership_display_value(self):
        return get_choice_display_value(self.ownership, commons.OWNERSHIP_CHOICES)
    
    @property
    def district_display_value(self):
        return get_choice_display_value(self.district, commons.DISTRICT_CHOICES)
    
    @property
    def local_body_display_value(self):
        return get_choice_display_value(self.local_body, commons.ALL_LOCALBODY_CHOICES)

industry_without_gis/forms.py
from django.forms import ModelForm
from django import forms

from .models import IndustryWithoutGis


class IndustryWithoutGisModelForm(ModelForm):
    industry_name = forms.CharField(required=True)
    
    def clean(self):
        cleaned_data = super().clean()
        for field_name in ['total_manpower', 'skillfull', 'unskilled', 'indigenous', 'foreign', 'male', 'female', 'total_capital', 'fixed_capital', 'current_capital', 'yearly_capacity']:
            if field_name in cleaned_data and cleaned_data[field_name] is None:
                cleaned_data[field_name] = 0
    
    class Meta:
        model = IndustryWithoutGis
        fields = "__all__"

industry_without_gis/views.py
import pandas as pd
import xlwt
import csv

from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.serializers import serialize
from django.db.models import Sum

from .models import IndustryWithoutGis
from .forms import IndustryWithoutGisModelForm

from fdip import commons
from fdip.decorators import superadmin_required
from .excel_name import *
from industry.views import session_local_delete
from report.excel_data_mapping import (
    dtype_mapping, sex_mapping, caste_mapping, investment_mapping, industry_acc_product_mapping, current_status_mapping, 
    ownership_mapping, raw_materials_source_mapping, current_running_capacity_mapping, district_mapping, local_body_mapping
    )


def industry_without_gis_home(request):
    session_local_delete(request)
    
    selected_district = request.GET.get('district')
    
    if selected_district:
        data_filter = IndustryWithoutGis.objects.filter(district=selected_district)
    else:
        data_filter = IndustryWithoutGis.objects.all()

    unique_districts = IndustryWithoutGis.objects.values_list('district', flat=True).distinct()

    district_count = unique_districts.count()
    
    total_industry = data_filter.count()
    #for showing chart acc to investment
    miniature = data_filter.filter(investment='MINIATURE').count()
    domestic = data_filter.filter(investment='DOMESTIC').count()
    small = data_filter.filter(investment='SMALL').count()
    medium = data_filter.filter(investment='MEDIUM').count()
    large = data_filter.filter(investment='LARGE').count()
    total_industry_acc_inv = miniature + domestic + small + medium + large
    #for showing chart acc to ownership
    private = data_filter.filter(ownership='PRIVATE').count()
    partnership = data_filter.filter(ownership='PARTNERSHIP').count()
    total_ownership = private + partnership
    #for showing chart acc to current status
    active = data_filter.filter(current_status='A').count()
    inactive = data_filter.filter(current_status='I').count()
    total_current_status = active + inactive
    #for showing chart acc to type of product
    energy = data_filter.filter(industry_acc_product='E').count()
    manufacturing = data_filter.filter(industry_acc_product='MF').count()
    ag = data_filter.filter(industry_acc_product='AF').count()
    mineral = data_filter.filter(industry_acc_product='MI').count()
    infra = data_filter.filter(industry_acc_product='I').count()
    tourism = data_filter.filter(industry_acc_product='T').count()
    it = data_filter.filter(industry_acc_product='IC').count()
    service = data_filter.filter(industry_acc_product='S').count()
    others = data_filter.filter(industry_acc_product='O').count()
    total_industry_acc_pro = (energy + manufacturing + ag + mineral + infra + 
                             tourism + it + service + others)
    #for showing chart acc to employment
    total_manpower = data_filter.aggregate(total=Sum('total_manpower'))['total']
    skilled = data_filter.aggregate(total=Sum('skillfull'))['total']
    unskilled = data_filter.aggregate(total=Sum('unskilled'))['total']
    indigenous = data_filter.aggregate(total=Sum('indigenous'))['total']
    foreign = data_filter.aggregate(total=Sum('foreign'))['total']
    male = data_filter.aggregate(total=Sum('male'))['total']
    female = data_filter.aggregate(total=Sum('female'))['total']

    context = {
                'unique_districts':unique_districts,
                'district_count':district_count,
                
                'total_industry': total_industry,
                
                'total_industry_acc_inv': total_industry_acc_inv,
                'miniature': miniature,
                'domestic': domestic,
                'small': small,
                'medium': medium,
                'large': large,
                
                'total_ownership': total_ownership,
                'private': private,
                'partnership': partnership,
                
                'total_current_status': total_current_status,
                'active': active,
                'inactive': inactive,
                
                'total_industry_acc_pro': total_industry_acc_pro,
                'energy': energy,
                'manufacturing': manufacturing,
                'ag': ag,
                'mineral': mineral,
                'infra': infra,
                'tourism': tourism,
                'it': it,
                'service': service,
                'others': others,
                'total_manpower': total_manpower,
                'skilled': skilled,
                'unskilled': unskilled,
                'indigenous': indigenous,
                'foreign': foreign,
                'male': male,
                'female': female,
                }
    if request.user.is_authenticated:
        return render(request, 'industry_without_gis/industry_without_gis_graph.html', context)
    else:
        return render(request, 'public/industry_without_gis_public.html', context)

@superadmin_required
def without_gis_data_import(request, file):
    """function for exporting excel data of industries without gis to IndutryWithoutGis model"""
    df = pd.read_excel(file, dtype=dtype_mapping)
    df.columns = df.columns.str.strip()     # Removes blank spaces from column names

    for _, row in df.iterrows():
        industry_data = {}
        
        if industry_name in df.columns:
            industry_name_value = row[industry_name]
            if pd.notna(industry_name_value):
                industry_data['industry_name'] = industry_name_value
            else:                                                   # Excel row not having industry_name value are not entered
                continue

        if reg_date in df.columns:
            reg_date_value = row[reg_date]
            if pd.notna(reg_date_value):
                try:
                    datetime_obj = pd.to_datetime(reg_date_value)
                    formatted_reg_date = datetime_obj.strftime('%Y-%m-%d')  # Format as 'YYYY-MM-DD'
                    industry_data['reg_date'] = formatted_reg_date
                except ValueError:
                    industry_data['reg_date'] = None

        column_names = {
            'industry_reg_no': industry_reg_no, 'owner_name': owner_name, 'address': address, 
            'telephone_number': telephone_number, 'contact_person': contact_person, 
            'mobile_number': mobile_number, 'ward_no': ward_no, 'settlement': settlement, 
            'product_description': product_description, 'product_service_name': product_service_name, 
            'machinery_tool': machinery_tool
        }
        for k, v in column_names.items():
            if v in df.columns:
                value = row[v]
                if pd.notna(value):
                    industry_data[k] = value

        
        column_mappings = {
            'sex': (sex, sex_mapping),
            'caste': (caste, caste_mapping),
            'investment': (investment, investment_mapping),
            'industry_acc_product': (industry_acc_product, industry_acc_product_mapping),
            'current_status': (current_status, current_status_mapping),
            'ownership': (ownership, ownership_mapping),
            'raw_material_source': (raw_material_source, raw_materials_source_mapping),
            'current_running_capacity': (current_running_capacity, current_running_capacity_mapping),
            'district': (district, district_mapping),
            'local_body': (local_body, local_body_mapping),
        }
        for column, mapping in column_mappings.items():
            if mapping[0] in df.columns:
                choice = row[mapping[0]]
                if pd.notna(choice):
                    industry_data[column] = mapping[1].get(choice.strip(), None)

        manpower_columns = {
            'male': male, 'female': female, 'skillfull': skillfull, 
            'unskilled': unskilled, 'indigenous': indigenous, 
            'foreign': foreign
        }
        for k, v in manpower_columns.items():
            if v in df.columns:
                manpower_value = row[v] if pd.notna(row[v]) else 0
                try:
                    int_manpower_value = int(manpower_value)
                except ValueError:
                    int_manpower_value = 0
                industry_data[k] = int_manpower_value
        # Stores value of total manpower (if one of the column is missing returns 0)
        total_manpower = industry_data.get('male', 0) + industry_data.get('female', 0)
        
        capital_columns = {
            'yearly_capacity': yearly_capacity, 'fixed_capital': fixed_capital, 
            'current_capital': current_capital, 'total_capital': total_capital
        }
        for k, v in capital_columns.items():
            if v in df.columns:
                capital_value = row[v] if pd.notna(row[v]) else 0
                clean_capital_value = str(capital_value).replace(',', '')  # Remove commas from the number
                try:
                    float_capital_value = float(clean_capital_value)
                except ValueError:
                    float_capital_value = 0
                industry_data[k] = float_capital_value
        
        if industry_data:
            industry = IndustryWithoutGis(**industry_data)
            if hasattr(industry, 'total_manpower'):
                industry.total_manpower = total_manpower
            industry.save() 
    return messages.success(request, "The excel data is saved to database.")


def without_gis_industry_list(request):
    districts = commons.DISTRICT_CHOICES
    all_localbody = commons.ALL_LOCALBODY_CHOICES
    if 'type' in request.session:

templates/industry_without_gis/industry_detail_without_gis.html
{% extends "layout/base.html" %}
{% load static %}
{% block container %}
    <div class="container my-5">
        <div class="kit-row">
            <h2 class="kit-page-heading">Industry Details Without GIS( उद्योग विवरण )</h2>
            <div class="kit-text-navigation"><span>Applicant Portal </span><img src="{% static '/image/arrow.png' %}" alt="">
                Industry Detail</div>
        </div>

        <div class="kit-form-container">
            <div class="kit-row mb-4">
                <h2 class="kit-page-heading">{{industry.industry_name}}</h2>
                
            </div>

            <div class="kit-row">
                <h2 class="kit-smpage-heading">Industry Details ( उद्योग विवरण )</h2>
                <div class="kit-btn-container">
                    <a href="{% url 'industry_without_gis_profile_pdf' industry_id=industry.id %}" class="kit-btn kit-info-btn">Download Pdf</a>
                    <a href="{% url 'edit_industry_without_gis' industry_id=industry.id %}" class="kit-btn kit-info-btn" target="_blank"><img src="{% static '/image/edit.png' %}" alt="">Update Info</a>
                </div>
            </div>
            <div class="kit-myindustry-detail mt-4">
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">उद्योगको नाम(Name of Industry)</p>
                        <h2 class="kit-industry-content">{{ industry.industry_name|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">उद्योग दर्ता मिति (Industry Registration No)</p>
                        <h2 class="kit-industry-content">{{ industry.industry_reg_no|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">उद्योग दर्ता मिति(Registration Date)B.S:</p>
                        <h2 class="kit-industry-content">{{ industry.reg_date|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">प्रोप्राइटरको नाम (Owner’s Name)</p>
                        <h2 class="kit-industry-content">{{ industry.owner_name|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">लिङ्ग (Sex)</p>
                        <h2 class="kit-industry-content">{{ industry.get_sex_display|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">जाती (Caste)</p>
                        <h2 class="kit-industry-content">{{ industry.get_caste_display|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">ठेगाना (Address)</p>
                        <h2 class="kit-industry-content">{{ industry.address|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">फोन नं.(Telephone no.)</p>
                        <h2 class="kit-industry-content">{{ industry.telephone_number|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">सम्पर्क व्यक्ति (Contact Person)</p>
                        <h2 class="kit-industry-content">{{ industry.contact_person|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">मोबाइल नं (Mobile No.)</p>
                        <h2 class="kit-industry-content">{{ industry.mobile_number|default_if_none:'----' }}</h2>
                    </div>
                </div>
            </div>

            <h2 class="kit-smpage-heading mt-5">Industry Address ( उद्योग ठेगाना )</h2>
            <div class="kit-myindustry-detail mt-4">
                <div class="row mb-4">
                    <div class="col-sm-3">
                        <p class="kit-industry-title">जिल्ला (District)</p>
                        <h2 class="kit-industry-content">{{ industry.get_district_display|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-3">
                        <p class="kit-industry-title">स्थानिय तह (Local Body)</p>
                        <h2 class="kit-industry-content">{{ industry.get_local_body_display|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-3">
                        <p class="kit-industry-title">वडा नं.(Ward No.)</p>
                        <h2 class="kit-industry-content">{{ industry.ward_no|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-3">
                        <p class="kit-industry-title">गाउँ/टोल/बस्ती (Settlement)</p>
                        <h2 class="kit-industry-content">{{ industry.settlement|default_if_none:'----' }}</h2>
                    </div>
                </div>
            </div>

            <div class="kit-myindustry-detail mt-4">
                <div class="row mb-4">
                    <div class="col-sm-12">
                        <p class="kit-industry-title">उद्योगले उत्पादन गर्ने बस्तु वा सेवाको विवरण (Product Description)
                        </p>
                        <h2 class="kit-industry-content">{{ industry.product_description|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">लगानीको प्रकृतिको आधारमा उद्योग(Industry in accordance to
                            Investment)</p>
                        <h2 class="kit-industry-content">{{ industry.get_investment_display|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">उद्योगको स्वामित्व (Ownership)</p>
                        <h2 class="kit-industry-content">{{ industry.get_ownership_display|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">कच्चा पदार्थको स्रोत ( Source of Raw Materials)</p>
                        <h2 class="kit-industry-content">{{ industry.get_raw_material_source_display|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">उत्पादनको आधारमा उद्योगको किसिम (Industry in accordance to
                            Product)</p>
                            <h2 class="kit-industry-content">{{ industry.get_industry_acc_product_display|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">उद्योगको वर्तमान अवस्था(Current Status)</p>
                        <h2 class="kit-industry-content">{{ industry.get_current_status_display|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">कुन क्षमतामा उद्योग संचालनमा छ? (Current Running Capacity)</p>
                        <h2 class="kit-industry-content">{{ industry.get_current_running_capacity_display|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">मेशिन औजारको विवरण (Machinery Tool)</p>
                        <h2 class="kit-industry-content">{{ industry.machinery_tool|default_if_none:'----' }}</h2>
                    </div>
                    {% if industry.industry_acc_product == 'O' %}
                        <div class="col-sm-6">
                            <p class="kit-industry-title">अन्य उद्योगको किसिमको विवरण (Industry in accordance to
                                Product Others description)</p>
                                <h2 class="kit-industry-content">{{ industry.others_text|default_if_none:'----' }}</h2>
                        </div>
                    {% endif %}
                </div>
            </div>

            <h2 class="kit-smpage-heading mt-4">उत्पादनको विवरण (Product Description)<h2>
            <div class="kit-myindustry-detail">
                <div class="row">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">वस्तु वा सेवाको नाम(Product Service Name)</p>
                        <h2 class="kit-industry-content">{{ industry.product_service_name|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">वार्षिक उत्पादन क्षमता(Yearly Capacity)</p>
                        <h2 class="kit-industry-content">{{ industry.yearly_capacity|default_if_none:'----' }}</h2>
                    </div>
                </div>
            </div>

            <h2 class="kit-smpage-heading mt-4">रोजगारीको अवस्था (Employment)<h2>
            <div class="kit-myindustry-detail">
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">जम्मा जनशक्ति संख्या (Total Manpower)</p>
                        <h2 class="kit-industry-content">{{ industry.total_manpower|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">विदेशी जनशक्ति संख्या(Foreign)</p>
                                        <h2 class="kit-industry-content">{{ industry.foreign|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">दक्ष जनशक्ति संख्या(Skill full)</p>
                        <h2 class="kit-industry-content">{{ industry.skillfull|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">पुरुष जनशक्ति संख्या(Male)</p>
                        <h2 class="kit-industry-content">{{ industry.male|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">अदक्ष जनशक्ति संख्या(Unskilled)</p>
                        <h2 class="kit-industry-content">{{ industry.unskilled|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-6">
                        <p class="kit-industry-title">महिला जनशक्ति संख्या(Female)</p>
                        <h2 class="kit-industry-content">{{ industry.female|default_if_none:'----' }}</h2>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <p class="kit-industry-title">स्वदेशी जनशक्ति संख्या(Indigenous)</p>
                        <h2 class="kit-industry-content">{{ industry.indigenous|default_if_none:'----' }}</h2>
                    </div>
                </div>
            </div>

            <h2 class="kit-smpage-heading mt-4">पुंजीको अवस्था (Capital)<h2>
            <div class="kit-myindustry-detail">
                <div class="row mb-4">
                    <div class="col-sm-4">
                        <p class="kit-industry-title">स्थिर पूँजी (Fixed Capital)</p>
                        <h2 class="kit-industry-content">{{ industry.fixed_capital|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-4">
                        <p class="kit-industry-title">चालु पूँजी (Current Capital)</p>
                        <h2 class="kit-industry-content">{{ industry.current_capital|default_if_none:'----' }}</h2>
                    </div>
                    <div class="col-sm-4">
                        <p class="kit-industry-title">जम्मा पूँजी (Total Capital)</p>
                        <h2 class="kit-industry-content">{{ industry.total_capital|default_if_none:'----' }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block customjs %}
    <script src="{% static '/js/locationdisplay.js' %}"></script>
{% endblock %}